name: bind_test
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  intl: ^0.17.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - lib/common/assets/icons/
    - lib/common/assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: lib/common/assets/fonts/Manrope-Regular.ttf
